apps/student/models.py
from datetime import datetime

from apps.app import db

class Student(db.Model):
    __tablename__ = "students"
    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.String, unique=True, index=True)
    nickname = db.Column(db.String, index=True)
    p_flag = db.Column(db.Boolean, default=False)
    group01 = db.Column(db.String)
    group02 = db.Column(db.String)
    group03 = db.Column(db.String)
    group04 = db.Column(db.String)
    group05 = db.Column(db.String)
    group06 = db.Column(db.String)
    group07 = db.Column(db.String)
    group08 = db.Column(db.String)
    group09 = db.Column(db.String)
    group10 = db.Column(db.String)
    group11 = db.Column(db.String)
    group12 = db.Column(db.String)
    group13 = db.Column(db.String)
    group14 = db.Column(db.String)
    group15 = db.Column(db.String)
    group16 = db.Column(db.String)
    group17 = db.Column(db.String)
    group18 = db.Column(db.String)
    group19 = db.Column(db.String)
    group20 = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    
    def is_duplicate_number(self):
        return Student.query.filter_by(number=self.number).first() is not None

apps/app.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from apps.config import config

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "auth.login" #login_viewのルート設定
login_manager.login_message = ""


def create_app(config_key="local"):
    app = Flask(__name__)
    app.config.from_object(config[config_key])

    db.init_app(app)
    Migrate(app, db)
    login_manager.init_app(app)

    from apps.student import views as student_views

    app.register_blueprint(student_views.student, url_prefix="/student")

    from apps.auth import views as auth_views

    app.register_blueprint(auth_views.auth, url_prefix="/auth")

    return app

apps/student/views.py
from flask import Blueprint, redirect, render_template, g, url_for, flash, request
from flask_login import login_required
from apps.student.form import AllUpdateForm, RegistForm, UpdateForm

from apps.student.models import Student
from apps.app import db

student = Blueprint("student", __name__, template_folder="templates", static_folder="static")

@student.route('/top')
@login_required
def top():
    student_list = db.session.query(Student).all()
    return render_template('student/top.html',student_list=student_list)

@student.route('/regist',methods=['GET','POST'])
@login_required
def regist():
    form = RegistForm()
        
    if form.validate_on_submit():
        print(form.data)
        # 画面からの登録情報の取得
        student = Student(
            number=form.number.data,
            nickname=form.nickname.data,
        )
        
        if student.is_duplicate_number():
            flash('指定の生徒番号は登録済みです。')
            return redirect(url_for('student.regist'))
        
        db.session.add(student)
        db.session.commit()
        return redirect(url_for('student.top'))

    return render_template('student/regist.html', form=form)

@student.route('/editall',methods=['GET','POST'])
@login_required
def edit_all():
    form = AllUpdateForm()
    student_list = db.session.query(Student).all()
    
    if form.all[0].validate_on_submit():
        print(form.all.data)
        # 画面からの登録情報の取得
        # student = Student(
        # number=form.number.data,
        # nickname=form.nickname.data,
        # )
        
        # if student.is_duplicate_number():
        #     flash('指定の生徒番号は登録済みです。')
        #     return redirect(url_for('student.regist'))
        
        # db.session.add(student)
        # db.session.commit()
        # return redirect(url_for('student.top'))
    #print(form.all.data)
    return render_template('student/editall.html',form=form, student_list=student_list)


@student.route('/<id>/edit',methods=['GET','POST'])
@login_required
def edit(id):
    form = UpdateForm()
    post = db.session.query(Student).filter_by(id=id).first()
        
    if form.validate_on_submit():
        student = Student(
            number=form.number.data,
            nickname=form.nickname.data,
        )
        
        if(student.number != post.number):
            flash('生徒番号は変更できません。')
            return redirect(url_for('student.edit',id=id))
        
        post.nickname=student.nickname
        
        db.session.commit()
        
        return redirect(url_for('student.top'))
    
    return render_template('student/edit.html', form=form, post=post)

@student.route('/<id>/delete',methods=['GET','POST'])
@login_required
def delete(id):
    post = db.session.query(Student).filter_by(id=id).first()
    
    if request.method == 'POST':
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for('student.top'))
    
    return render_template('student/delete.html', post=post)

apps/templates/student/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <a href="{{ url_for('auth.logout') }}" role="button">ログアウト</a>
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>    
</body>
</html>

apps/templates/student/delete.html
{% extends 'student/base.html' %}

{% block title %}生徒情報削除{% endblock %}

{% block content %}
<div>
    <header>生徒情報削除</header>

    <p>以下の情報を削除しますか?</p>
    <section>
        <form method="POST">
            <p>{{ post.number }}</p>
            <p>{{ post.nickname }}</p>
            <p><input type="submit" value="削除"></p>
        </form>

    <a href="{{ url_for('student.top') }}" role="button">一覧に戻る</a>

    </section>

</div>
{% endblock %}

apps/templates/student/edit.html
{% extends 'student/base.html' %}

{% block title %}生徒情報更新{% endblock %}

{% block content %}
<div>
    <header>生徒情報更新</header>
    <section>
        <form
            method="post"
            action="{{ url_for('student.edit', id=post.id)}}"
        >
        {{ form.csrf_token }}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-error">
                {{ message }}
            </div>
        {% endfor %}
    
        {% for field, errors in form.errors.items() %}
            <div class="alert alert-error">
                {{ form[field].label }}: {{ ', '.join(errors) }}
            </div>
        {% endfor %}

        <p>{{ form.number(size=30, placeholder="number", value=post.number) }}</p>
        <p>{{ form.nickname(size=30, placeholder="nickname", value=post.nickname) }}</p>
        <p>{{ form.submit() }}</p>
        </form>

    <a href="{{ url_for('student.top') }}" role="button">一覧に戻る</a>

    </section>

</div>
{% endblock %}

apps/templates/student/editall.html
{% extends 'student/base.html' %}

{% block title %}生徒情報一括更新{% endblock %}

{% block content %}
<div>
    <header>生徒情報一括更新</header>
    <section>
        <form
            method="post"
            action="{{ url_for('student.edit_all')}}"
        >
            {{ form.all[0].csrf_token }}



            {% for message in get_flashed_messages() %}
                <div class="alert alert-error">
                    {{ message }}
                </div>
            {% endfor %}
        
            {#{% for field, errors in form.errors.items() %}
                <div class="alert alert-error">
                    {{ form[field].label }}: {{ ', '.join(errors) }}
                </div>
            {% endfor %}#}


            
            <table border="1">
                <tr>
                    <th>number</th>
                    <th>nickname</th>
                </tr>
                {% for student in student_list %}
                    <tr>
                        <td>{{ form.all[loop.index-1].number(size=30, placeholder="number",value=student.number) }}</td>
                        <td>{{ form.all[loop.index-1].nickname(size=30, placeholder="number",value=student.nickname) }}</td>
                    </tr>
                {% endfor %}
            </table>

            <p>{{ form.submit() }}</p>

        </form>

    <a href="{{ url_for('student.top') }}" role="button">一覧に戻る</a>

    </section>

</div>
{% endblock %}

apps/templates/student/regist.html
{% extends 'student/base.html' %}

{% block title %}生徒新規登録{% endblock %}

{% block content %}
<div>
    <header>生徒新規登録</header>
    <section>
        <form
            method="post"
            action="{{ url_for('student.regist', next=request.args.get('next')) }}"
        >

        {{ form.csrf_token }}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-error">
                {{ message }}
            </div>
        {% endfor %}
    
        {% for field, errors in form.errors.items() %}
            <div class="alert alert-error">
                {{ form[field].label }}: {{ ', '.join(errors) }}
            </div>
        {% endfor %}
    
        <p>{{ form.number(size=30, placeholder="number") }}</p>
        <p>{{ form.nickname(size=30, placeholder="nickname") }}</p>
        <p>{{ form.p_flag(size=30, placeholder="p_flag") }}</p>
        <p>{{ form.submit() }}</p>
        </form>

    <a href="{{ url_for('student.top') }}" role="button">一覧に戻る</a>

    </section>

</div>
{% endblock %}

apps/templates/student/top.html
{% extends 'student/base.html' %}

{% block title %}最適化アプリ{% endblock %}

{% block content %}

<header>最適化アプリ</header>
    <a href="{{ url_for('student.regist') }}"role="button">新規登録</a>
    <a href="{{ url_for('student.edit_all') }}" role="button">一括編集</a>
    {% if student_list == [] %}
        <p>リストが登録されていません。</p>
    {% else %}
        <table border="1">
            <tr>
                <th>number</th>
                <th>nickname</th>
                <th>次回出席</th>
                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
                <th>6</th>
                <th>7</th>
                <th>8</th>
                <th>9</th>
                <th>10</th>
                <th>11</th>
                <th>12</th>
                <th>13</th>
                <th>14</th>
                <th>15</th>
                <th>16</th>
                <th>17</th>
                <th>18</th>
                <th>19</th>
                <th>20</th>
            </tr>
            {% for student in student_list %}
                <tr>
                    <td>{{student.number}}</td>
                    <td>{{student.nickname}}</td>
                    <td>{{student.p_flag}}</td>
                    <td>{{student.group01}}</td>
                    <td>{{student.group02}}</td>
                    <td>{{student.group03}}</td>
                    <td>{{student.group04}}</td>
                    <td>{{student.group05}}</td>
                    <td>{{student.group06}}</td>
                    <td>{{student.group07}}</td>
                    <td>{{student.group08}}</td>
                    <td>{{student.group09}}</td>
                    <td>{{student.group10}}</td>
                    <td>{{student.group11}}</td>
                    <td>{{student.group12}}</td>
                    <td>{{student.group13}}</td>
                    <td>{{student.group14}}</td>
                    <td>{{student.group15}}</td>
                    <td>{{student.group16}}</td>
                    <td>{{student.group17}}</td>
                    <td>{{student.group18}}</td>
                    <td>{{student.group19}}</td>
                    <td>{{student.group20}}</td>
                    <td>
                        <a href="{{ url_for('student.edit', id=student.id) }}" role="button">編集</a>
                        <a href="{{ url_for('student.delete', id=student.id) }}" role="button">削除</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}